version: '3.8'

services:
  mastra-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab-code-review-mastra
    image: gitlab-code-review-mastra:latest
    ports:
      - "4111:4111"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mastra-network

networks:
  mastra-network:
    driver: bridge
